version: "3.9"
services:
  backend:
    container_name: spotify_backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
  frontend:
    container_name: spotify_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
    - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend